// Generated by build.rs
// This file provides module structure for tests

// Note: Full WASM functionality may not be available on all platforms
// particularly on Mac M1 systems due to secp256k1-sys compilation issues
// See: https://github.com/rust-bitcoin/rust-secp256k1/issues/283

// Uncomment when WebAssembly build is successful:
// pub mod yield_vault_build;
