[package]
name = "secp256k1-sys"
version = "0.9.3"  # This version needs to match the dependency version in Cargo.lock
edition = "2021"
links = "secp256k1"
authors = ["YieldVault Contributors"]
description = "Stub implementation of secp256k1 system library required by Bitcoin dependencies."
repository = "https://github.com/rust-bitcoin/rust-secp256k1"
license = "MIT"
readme = "README.md"
exclude = ["tests"]

[build-dependencies]
cc = { version = "1.0.79", features = ["parallel"], optional = true }
bindgen = { version = "0.66", optional = true }

[dependencies]
libc = "0.2"

[features]
default = []
# Disable system-secp256k1 feature for WebAssembly build
